name = "clubsPlatform"
compatibility_date = "2024-09-23"
pages_build_output_dir = "website/dist"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "clubsPlatform-auth"
database_id = "97a5772c-41a2-4674-904a-251dbe0473f6"
preview_database_id = "634c6b97-01dd-41f1-b704-74a8da8a5f2b"
migrations_table = "migrations"
migrations_dir = "migrations"

[vars]
BETTER_AUTH_SECRET = "62f48b394825b463f73394328543d9c2c7584e861af297828300da636a312d42"
